version: '3'

services:
  frontend:
    build:
      context: ./react-app/
    volumes:
      - react_build:/react/build
  nginx:
    image: nginx:latest
    ports:
      - 8000:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - frontend
volumes:
  react_build: